name: "Great Idea 💡"
description: Your Good Idea
title: "Good Idea"
labels: [idea]
body:
- type: markdown
  attributes:
    value: "If the idea is related to the operation or display of the website, you've come to the right place"
- type: textarea
  attributes:
    label: "Describe your idea to add to the page"
