name: "Great Idea 💡"
description: Your Good Idea
title: "Good Idea"
labels: [idea]
body:
- type: markdown
  attributes:
    value: "If the idea is related to the operation or display of the website, you've come to the right place"
- type: checkboxes
  id: chk_result
  attributes:
    label: "What do you have an idea for"
    description: You may select more than one,
    options:
      - label: "index.html | Main Page"
      - label: "main.js | Page Script"
      - label: "defualt.css | Page Layout/Responsive"
      - label: "other"
- type: textarea
  attributes:
    label: "Describe your idea to add to the page"
